# CoreDNS is disabled on GKE as it uses kube-dns, enable it on EKS as it uses CoreDNS
---
kubeScheduler:
  enabled: true
kubeControllerManager:
  enabled: true
coreDns:
  enabled: false
kubeProxy:
  enabled: true
