prometheus:
  server:
    persistentVolume:
      enabled: false
  #prometheusSpec:
  #  storageSpec:
  #    volumeClaimTemplate:
  #      spec:
  #        accessModes: ["ReadWriteOnce"]
  #        resources:
  #          requests:
  #            storage: 0Gi