# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
---
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: false
  #prometheusSpec:
  #  storageSpec:
  #    volumeClaimTemplate:
  #      spec:
  #        accessModes: ["ReadWriteOnce"]
  #        resources:
  #          requests:
  #            storage: 10Gi
