apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackbox-exporter.fullname" . }}
  labels:
    {{- include "blackbox-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: blackbox-port
      protocol: TCP
      name: blackbox-port
  selector:
    {{- include "blackbox-exporter.selectorLabels" . | nindent 4 }}
